const blogData = [
  {
    id: 1,
    title: "Coming Soon: Exciting Blogs Ahead!",
    desc: "Stay tuned for amazing insights, stories, and guides from our team.",
    date: "TBA",
    category: "Announcements",
    readTime: "—",
    image: "https://picsum.photos/id/1015/1200/750",
  },
  {
    id: 2,
    title: "Our Blog is Under Construction",
    desc: "We’re preparing something awesome for you. Check back soon!",
    date: "TBA",
    category: "Updates",
    readTime: "—",
    image: "https://picsum.photos/id/1033/1200/750",
  },
  {
    id: 3,
    title: "Stay Connected for Latest News",
    desc: "Follow us for fresh updates and content drops right here.",
    date: "TBA",
    category: "News",
    readTime: "—",
    image: "https://picsum.photos/id/1024/1200/750",
  },
  {
    id: 4,
    title: "Insights That Inspire — Coming Soon!",
    desc: "We’re crafting content that will empower you to think, act, and innovate smarter.",
    date: "TBA",
    category: "Insights",
    readTime: "—",
    image: "https://picsum.photos/id/1040/1200/750",
  },
  {
    id: 5,
    title: "Behind the Scenes at Anslation",
    desc: "A sneak peek into our creative process, team stories, and culture.",
    date: "TBA",
    category: "Culture",
    readTime: "—",
    image: "https://picsum.photos/id/1005/1200/750",
  },
  {
    id: 6,
    title: "New Perspectives, Fresh Ideas",
    desc: "Our thought leaders are curating topics that challenge the ordinary.",
    date: "TBA",
    category: "Thought Leadership",
    readTime: "—",
    image: "https://picsum.photos/id/1043/1200/750",
  },
  {
    id: 7,
    title: "Digital Innovation Hub — Launching Soon",
    desc: "Explore trends and technologies driving digital transformation.",
    date: "TBA",
    category: "Technology",
    readTime: "—",
    image: "https://picsum.photos/id/1050/1200/750",
  },
  {
    id: 8,
    title: "Empowering Businesses Through Strategy",
    desc: "We’ll soon share expert strategies and success stories from our partners.",
    date: "TBA",
    category: "Business",
    readTime: "—",
    image: "https://picsum.photos/id/1060/1200/750",
  },
  {
    id: 9,
    title: "AI, Cloud, and Data — The Future is Here",
    desc: "Discover how technology is shaping industries in the upcoming blog series.",
    date: "TBA",
    category: "Innovation",
    readTime: "—",
    image: "https://picsum.photos/id/1074/1200/750",
  },
];

export {blogData};